Python lists vs Numpy Arrays
1. Numpy arrays are faster
2. Numpy arrays stores data in continuous memory blocks
3. It uses less memory
4. Supports direct vectorized operations
5. Built-in mathematical functions

In [9]:
import numpy as np

In [13]:
array1D = np.array([1,2,3,4,5,6])
print(array1D, type(array1D))

array2D = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12], [13,14,15,16,17,18]])
print(array2D, type(array2D))

[1 2 3 4 5 6] <class 'numpy.ndarray'>
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]] <class 'numpy.ndarray'>


## Array Creation Functions

- `np.zeros((r,c))` creates an array filled with 0s.
- `np.ones((r,c))` creates an array filled with 1s.
- `np.full((r,c), value)` creates an array filled with a specified value.
- Shape is always written as `(rows, columns)`.


In [22]:
#first come the rows and then the columns
array1 = np.zeros((2,3))
print(array1, array1.shape)
print('--------------')
array2 = np.ones((2,3))
print(array2, array2.shape)
print('--------------')
array3 = np.full((2,3), 7)
print(array3, array3.shape)
print('--------------')
array4 = np.eye((3))
print(array4, array4.shape)
print('--------------')
array5 = np.arange(0,10,2)
print(array5, array5.shape)
print('--------------')
array5 = np.linspace(0,100,20)
print(array5, array5.shape)


[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)
--------------
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
--------------
[[7 7 7]
 [7 7 7]] (2, 3)
--------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
--------------
[0 2 4 6 8] (5,)
--------------
[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ] (20,)


## Important Array Properties

- `shape` → dimensions of the array.
- `size` → total number of elements.
- `dtype` → data type of elements.
- `ndim` → number of dimensions.


In [23]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a.shape)
print(a.size)
print(a.dtype)
print(a.ndim)

(3, 3)
9
int64
2


## Reshaping Arrays

- `reshape(rows, columns)` changes the arrangement of elements.
- Total elements must remain the same.
- Example: 6 elements can become `(2,3)` or `(3,2)` but not `(2,4)`.


In [27]:
b = np.array([[1,2], [4,5], [7,8]])
print(b, b.shape)

reshaped_b = b.reshape(2,3)
print(reshaped_b, reshaped_b.shape)

[[1 2]
 [4 5]
 [7 8]] (3, 2)
[[1 2 4]
 [5 7 8]] (2, 3)


## Indexing

- Indexing starts from 0.
- `array[row][column]` accesses a specific element.
- Negative indices access elements from the end.


In [31]:
array = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
print(array[0][3])

4


## Python List Slicing

- Slicing a Python list creates a **copy**.
- Changes in the sliced list do not affect the original list.


In [ ]:
numbers = [1,2,3,4,5,6] #A copy is created instead of a view in list
sub_list = numbers[1:4] 
print(sub_list)
sub_list[0] = 100
print(sub_list)
print(numbers)

[2, 3, 4]
[100, 3, 4]
[1, 2, 3, 4, 5, 6]


## NumPy Slicing

- Slicing a NumPy array usually creates a **view**.
- Changes in the sliced array can affect the original array.
- Use `.copy()` if you want an independent copy.


In [ ]:
numbers = np.array([1,2,3,4,5,6]) #A view is created
sub_list = numbers[1:4] 
print(sub_list)
sub_list[0] = 100
print(sub_list)
print(numbers)

[2 3 4]
[100   3   4]
[  1 100   3   4   5   6]


#Axis in multi-dimensional arrays
1D---> 1 Axis (axis 0)
2D---> 2 Axis (axis 0 -- rows, axis 1 -- columns)
3D---> 3 Axis (axis 0 -- depth, axis 1 -- rows, axis 2 -- columns)

## Vectorization

- NumPy performs operations on entire arrays at once.
- Faster than using Python loops.
- Example: `numbers**2` squares every element.


In [ ]:
numbers = np.array([1,2,3,4,5,6]) #vectorisation
print(numbers**2)

[ 1  4  9 16 25 36]


## Broadcasting Rules

- Compare dimensions from **right to left**.
- Two dimensions are compatible if:
  1. They are equal, or
  2. One of them is 1.
- Example:
  - `(2,3)` + `(3,)` ✓
  - `(2,3)` + `(2,1)` ✓
  - `(2,3)` + `(2,)` ✗


In [ ]:
#Vectorization
#Adding [1,2,3,4,5] and 5
#It starts with right to left. Two dimensions are compatible when they are equal or one of them is 1
a = np.array([1,2,3,4,5])
result = a + 5 #(1x5) + 1
print(result)

[ 6  7  8  9 10]


## Vector Normalization (Z-Score)

Formula:

`Z = (x - mean) / standard deviation`

Why normalize?
- Brings values to a similar scale.
- Helps machine learning models train better.
- Mean becomes approximately 0 and standard deviation becomes 1.


In [ ]:
#Vector Normalization (Z score)
arr = np.array([[1,2], [3,4]])
mean = np.mean(arr)
std_dev = np.std(arr)
normalized_arr = (arr-mean)/ std_dev
print(normalized_arr)
# normalized_arr would have mean = 0 and std =1

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
